A bunch of bug fixes, changes, fixing things that had broke and saving vendor items, Details in Finnish below
DONE, ainakin näyttää toimivan ellei jossain ole joku bugi vielä:
-Vendoreiden tavaroiden seivaus. Jotain funktionalisuutta oli hahmoteltu, mutta näköjään ei toiminut oikein ja jäänyt pahastikin kesken.

DONE, ellei jossain huomaamatonta bugia:
-jos vendorilla on vain nolla tavaraa, arvo uudet!

DONE:
-kaupparuutuun sorttaukset. Varmaan nappeja pari kappaletta sinne. Paino, arvo ja nimi?

DONE:
(korjaus: suljetaan headsup-kauppa aina inventoryn sulkemisen yhteydessä?)
-resurssipickup promptiin oikeat määrät, huom inventoryn määrä! Nämä eivät mene nyt oikein ja synkassa. Joskus puuttuu oikea määrä, joskus on oikein. Mitä tässä tapahtuu?
Ja jos myy kaiken, ei tule kauppaan enää uudestaan resurssia kerätessä, vaikka resourcehud näyttää vaikka että resurssia olisi vaikka seitsemän?
Tämä tapahtuu kuitenkin vain silloin, kun heads-up kauppa on jätetty päälle! Ehkä auttaisi, jos sen sulkisi inventoryn sulkiessa?

DONE:
(korjaus: sama korjaus kuin yllä)
-jostain syystä headsup-shoppiin lisätään nyt taas playeritemit tuplana (joskus!). Mitvit?

DONE:
(korjaus: ei lisätä itemeita joita on nolla)
-kaupparuutuun tuli resurssi-itemeitä, joita oli nolla kappaletta

DONE:
-lisää draggayssensitiivisyyttä kaupparuutuihin

DONE:
(korjaus: Piti vain revertata FirstPersonControllerPrefab, kun siellä oli aktivoimattomia objekteja)
-jostain syystä maapalloskenessä ei tule "rock contains x" promptia.

DONE:
(korjaus: Inventoryssa rivillä 428 käytettiin itemToAdd -muuttujan painoa ja sinne oli jäänyt viimeinen lisätty item, eli sandwich.
Inventoryssa käytetty tapa lisätä referenssi ja sitten instantioida ja initialisoida objekti tämän muuttujan kautta on varsin ikävä
ja tulevaisuutta silmällä pitäen pitäisi varmaankin refaktoroida alkuperäinen tapa pois)
-resurssien painot ei näy oikein inventoryssa.
Miksi ei? Miksi kaikki painaa 0.2, vaikka ItemSO:hon on asetettu painot oikein? Missä nämä asetetaan 0.2:een?
Jostain syystä resurssit kaikki käyttävät voileivän painoa. Sieltä tulee se 0.2

DONE:
-puuttuvat context menut (ContextMenu, rivi 25 eteenpäin)

DONE kai, näyttää nyt oikein hyvältä
-bugitarkistukset ItemSO -muutoksen jäljiltä.

DONE:
-inventoryyn ei näköjään nyt taas lisätä kerättyjä kamoja. Miksi ei? resourceInventory-script oli muutettu alta erilaiseksi ja dictionary-pohjaiseksi.

DONE:
-lisää draggayssensitiivisyyttä kaupparuutuihin

DONE:
-painon tsekkaus poimiessa takasin toimintaan.
DONE:
-Myös muuten inventoryn painot vinksallaan . Vinksallaan Ainakin porien kohdalla. Paino vaihtelee equippauksen mukaan, mutta jostain syystä advanced drill voi ollla inventaariossa ja equippattuna yhtaikaa. Mitä tässä tapahtuu?. katso alempi

DONE: porat
-ja miksi euippatut itemit ylipäätään poistetaan inventaariosta? Ehkei pitäisi. Ainakin painon pitäisi säilyä. Ja uniequippaus ja equippaus sekoittavat jotenkin inventaarion. Kokeillaan ilman poistoa inventaariosta. Ainakin paino-ongelman ratkaisee tuo.

DONE: spacesuit
- spacesuit poistetaan jossain hämärässä yhteydessä... joka löytyi. Shipweaponit vois kyllä varmuudeksi toistaiseksi poistaa inventorysta equippauksen yhteydessä, ettei voi laittaa yhtä itemiä molempiin slotteihin

DONE: ei voi enää
-voi laittaa equippia ja discardata itemin, jolloin item säilyy slotissa.

DONE:
.toString("0.0") lisätty painon näyttöön. -inventoryssa tulee floattien ja doublejen kanssa painoon sellainen pienidesimaalinen ja pitkä luku mahdollisesti

DONE:
-drill menee vahingossa spacesuit-slottiin

DONE:
-porattavat kivet spawnaavat random-kamaa planeetoilla. Tuli ongelmia collidereiden ja rigidbodyjen kanssa, eikä meinannut hommat oikein lähteä toimimaan. Lisäksi terrain saattoi päästää läpi putoavia resursseja. Varmaan siksi, että on niin ohut. Tämä korjaantui lisäämällä Ground-boxcolliderin kiven alle

DONE:
-lisää painot ja muut tavaroiden scriptable objecteihin. Myös kuvaukset lisätty

DONE:
-iteminfo-laatikoiden koko voisi olla pienempi, ettei mene ruudulta yli.

DONE:
-poista ylimääräiset testinapit inventaariosta ja jätä oleelliset vielä. Kato, että ruudut avautuvat ja sulkeutuvat fiksusti, eikä esim. päällekkäin.

DONE, ainakin suurin osa _turhista_, jotain toistaiseksi tarpeellisia on jätetty:
-kommentoi pois turhat tekstilogit, ettei konsoli ole täynnä roskaa!

DONE (oli ei-aktiivisena hierarkiassa ja siksi ei näkynyt.):
-jostain syystä ei nyt ContextMenut toimi

DONE, ei tule enää:
kun avaa headsup-shopin menun kautta, tulee: IndexOutOfRangeException: Index was outside the bounds of the array.
ShopHeadsUp.AddVendorItems () (at Assets/Scripts/ShopHeadsUp.cs:158)
ShopHeadsUp.StartShopping () (at Assets/Scripts/ShopHeadsUp.cs:71)
CanvasScript.ShowHeadsUpShop () (at Assets/Inventory/Scripts/CanvasScript.cs:62)
UnityEngine.Events.InvokableCall.Invoke () (at <7b2a272e51214e2f91bbc4fb4f28eff8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <7b2a272e51214e2f91bbc4fb4f28eff8>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)

DONE:
-item catalogiin puuttuvat uudet tyypit. Ehkä paljonkin refaktorointia. Muuten onnistui heti lisäykset, mutta jostain syystä sandwich menee myös fueleihin? Pahan onnen voileipä, kun aina aiheuttaa ongelmia. Itseasiassa edellisen näkymän itemit kokonaan tulevat osaksi fueleita. Listaa ei vissiin clearata asiallisesti? Syypääksi osoittautuikin väärä metodikutsu napissa.

DONE:
(korjaus: luodaan vaan uusi vendori null checkin jälkeen)
-jostain syystä nyt taas on hajonnut heads up kaupparuutu, kun siihen menee suoraan planeettaskenen kautta. Vendoria ei ole tietenkään. Toimii normaalisti WorldMapin kautta

DONE:
-mistä tämä tulee? Ainakin heti Startissa koitetaan laittaa ShowAll. Jos ItemCatalogi on aktiivisena hierarkiassa, tulee tämä errori. Refaktoroi myöhemmin, jos tarvetta
NullReferenceException: Object reference not set to an instance of an object
ItemCatalogItem.Awake () (at Assets/Inventory/Scripts/ItemCatalog/ItemCatalogItem.cs:31)
UnityEngine.Object:Instantiate(Object, Transform)
ItemCatalog:CreateItem(ItemSO) (at Assets/Inventory/Scripts/ItemCatalog/ItemCatalog.cs:110)
ItemCatalog:ShowAllItems() (at Assets/Inventory/Scripts/ItemCatalog/ItemCatalog.cs:62)
ItemCatalog:ShowAll() (at Assets/Inventory/Scripts/ItemCatalog/ItemCatalog.cs:197)
ItemCatalog:Start() (at Assets/Inventory/Scripts/ItemCatalog/ItemCatalog.cs:53)